name: edtrack
description: Edumarshal client for AKGEC

publish_to: "none"

version: 1.4.5+16

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  calendar_appbar: ^0.0.6
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.5
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^8.1.0
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  lottie: ^1.4.3
  package_info_plus: ^1.4.3
  paged_vertical_calendar: ^1.1.4
  path_provider: ^2.0.11
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  hive_generator: ^1.1.3
  injectable_generator: ^1.5.4
  integration_test:
    sdk: flutter
  json_serializable: ^6.5.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: "assets/ic_launcher.png"
  image_path_ios: "assets/ic_launcher.png"
  adaptive_icon_background: "#ffc0c0"
  adaptive_icon_foreground: "assets/ic_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
